<?php
define('THUNDERHAWK','thunderhawk');
define('APP_PATH',realpath('../../').'/');
define('API_PATH',realpath(__DIR__.'/../').'/');
define('CORE_PATH',realpath(API_PATH.'/../').'/');
define('TIME_ONE_HOUR',60*60);
define('TIME_ONE_DAY',TIME_ONE_HOUR*24);
define('TIME_ONE_WEEK',TIME_ONE_DAY*7);
define('TIME_ONE_YEAR',TIME_ONE_WEEK*52);